name: release-buildx

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  buildx:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set Release Tag Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - 
        name: docker hub login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      -
        name: Run Buildx
        env: 
          GITHUB_REPO: binetsky/netshoot
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --file ./Dockerfile \
            --tag $GITHUB_REPO:$GITHUB_SHA \
            --tag $GITHUB_REPO:$RELEASE_VERSION \
            --tag $GITHUB_REPO:latest .


            
